name: Release cisraeliqueue

on:
  release:
    types: [published]

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify version
        run: |
          TOML_VER=$(awk "/version =/ { print \$3 }" pyproject.toml)
          echo pyproject.toml version - "$TOML_VER"
          TAG_VER=\"${{ github.event.release.tag_name }}\"
          echo Tag version $TAG_VER
          [[ $TAG_VER == $TOML_VER ]]
  build:
    needs: check_version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.12", "3.13.0-rc.2"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install build dependencies
        run: pip install build
      - name: Build wheel
        run: pipx run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/*
  upload_test_pypi:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Test PyPi
      url: https://test.pypi.org/p/cisraeliqueue
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true
      - name: Release to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            repository-url: https://test.pypi.org/legacy/

  upload_production_pypi:
    needs: upload_test_pypi
    runs-on: ubuntu-latest
    environment:
      name: Production PyPi
      url: https://pypi.org/p/cisraeliqueue
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: 'dist/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        
