name: Release cisraeliqueue

on:
  release:
    types: [published]

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify version
        run: |
          TOML_VER=$(awk "/version =/ { print \$3 }" pyproject.toml)
          echo pyproject.toml version - "$TOML_VER"
          TAG_VER=\"${{ github.event.release.tag_name }}\"
          echo Tag version $TAG_VER
          [[ $TAG_VER == $TOML_VER ]]
  build:  # TODO: Use cibuildwheel, with env var CIBW_BUILD
    needs: check_version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is the latest version of Intel macOS
        os: [ubuntu-latest, macos-latest, macos-13, windows-latest]
        python-version: ["3.12", "3.13.0-rc.2"]
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.1
        env:
          CIBW_BUILD: "cp311-* cp312-* cp313-*"
          CIBW_BEFORE_BUILD: "pip install '.[dev]'"
        with:
          output-dir: dist
      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/*
  upload_test_pypi:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Test PyPi
      url: https://test.pypi.org/p/cisraeliqueue
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true
      - name: Release to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            repository-url: https://test.pypi.org/legacy/

  upload_production_pypi:
    needs: upload_test_pypi
    runs-on: ubuntu-latest
    environment:
      name: Production PyPi
      url: https://pypi.org/p/cisraeliqueue
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true
      - uses: AButler/upload-release-assets@v3.0
        with:
          files: 'dist/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        
